#!/usr/bin/env python

import psutil, commands, os, sys, subprocess, re

@author "Viktor Petersson"
@www "http://viktorpetersson.com"

# Get variables from config
host = os.environ['host']
port = os.environ['port']
user = os.environ['user']
userpwd = os.environ['userpwd']
timeout = 5

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print 'yes'

elif len(sys.argv) == 2 and sys.argv[1] == "config":
	print 'graph_title Pgpool-II'
	print 'graph_args --base 1000 -l 0'
	print 'graph_vlabel number of connections'
	print 'graph_category Postgresql'
	print 'graph_info This graph monitors the number of connections to Pgpool-II.'
	print 'wait.label Wait for connection'
	print 'wait.info The number of wait for connection request.'
	print 'idle.label Idle connections'
	print 'idle.info The number of idle in transaction.'
	print 'max.label num_init_children'
	print 'max.info Maximum number of connections (num_init_children).'

else:
    waitCount = 0
    idleCount = 0

    pl = psutil.process_iter()
    
    for item in pl:
        if ("wait for connection request" in str(item) and not "PCP" in str(item)):
            waitCount += 1
        elif ("idle in transaction" in str(item) and not "PCP" in str(item)):
            idleCount += 1
    
    pcpstatus = subprocess.check_output(["pcp_pool_status", str(timeout), host, port, user, userpwd])

    match = re.search(r'(name\s+:\s+num_init_children)\nvalue:\s(\d+)', pcpstatus)
    if match:
        maxCount = match.group(2)
    else:
        maxCount = "NaN"

    print "wait.value " + str(waitCount)
    print "idle.value " + str(idleCount)
    print "max.value " + str(maxCount)
